package me.mad4a.calendarwatcher.data;

import android.content.ContentResolver;
import android.database.Cursor;
import android.net.Uri;

import java.util.List;

/**
 * User: chsc4698@gmail.com
 * Date: 12-3-15
 * all rights reserved
 */
public abstract class Querier<T> {

	protected final ContentResolver contentResolver;

	public Querier(ContentResolver contentResolver) {
		this.contentResolver = contentResolver;
	}

	protected abstract Uri.Builder genBuilder();

	protected abstract Cursor postQuery(Uri.Builder builder);

	protected abstract List<T> fetch(Uri.Builder builder);

	/**
	 * notice: this method does not close cursor!
	 * @param cursor cursor to traverse
	 * @param handler what to do with the data that the cursor points to
	 * @param outputs outputs generated by handler
	 * @return if eventCursor is null, then return false, otherwise return true
	 */
	protected boolean traverseCursor(Cursor cursor, TraverseHandler<T> handler, List<T> outputs) {
		if (cursor != null) {
			if (cursor.moveToFirst()) {
				do {
					T output = handler.handle(cursor);
					if (outputs == null) {
						continue;
					}
					outputs.add(output);
				} while (cursor.moveToNext());
			}

			return true;
		} else {
			return false;
		}
	}
}
